# Generated by Django 4.2.1 on 2023-05-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criarConta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='registro_funcional',
            field=models.CharField(max_length=10),
        ),
    ]
